#!/bin/sh
# Find the next free erlang nodename using epmd  

EXISTING_NAMES=`epmd -names`
DEP_EBINS=`find deps -type d | grep -v \/test\/ | grep ebin`

CLIENT_INDEX=0
CLIENT_NAME="client$CLIENT_INDEX"

has_existing_name() {
  echo $EXISTING_NAMES | grep $1
  return $?
}

has_existing_name $CLIENT_NAME
while [ $? -eq 0 ]; do
    CLIENT_INDEX=`expr $CLIENT_INDEX + 1`
    CLIENT_NAME="client$CLIENT_INDEX"
    has_existing_name $CLIENT_NAME
done

exec erl \
    -pa "`dirname $0`/../ebin" \
    -pa $DEP_EBINS \
    -s reloader \
    -name $CLIENT_NAME \
    $@
